@extends('admin.layouts.app')

@section('title', 'Trang chủ')
@section('page_title', 'Quản lý trang chủ')

@section('content')
<div class="card"><div class="card-header d-flex flex-wrap gap-2 justify-content-between align-items-center"><div><h5 class="card-title mb-1">Cấu trúc section trang chủ</h5><p class="text-muted mb-0">Quản lý section chính và các section con theo từng ngôn ngữ.</p></div><a href="{{ route('admin.homepage-sections.create', ['locale' => $locale]) }}" class="btn btn-primary">Thêm section chính</a></div><div class="card-body"><ul class="nav nav-pills mb-4">@foreach($locales as $code => $name)<li class="nav-item"><a class="nav-link {{ $locale === $code ? 'active' : '' }}" href="{{ route('admin.homepage-sections.index', ['locale' => $code]) }}">{{ $name }}</a></li>@endforeach</ul>
@forelse($sections as $section)<div class="border rounded mb-3 overflow-hidden"><div class="d-flex flex-wrap gap-2 align-items-center justify-content-between p-3 bg-light"><div class="d-flex align-items-center gap-2">@if($section->icon_path)<img src="{{ asset($section->icon_path) }}" alt="" class="rounded bg-white border p-1" style="height:36px;width:36px;object-fit:contain">@endif @if($section->image_path)<img src="{{ asset($section->image_path) }}" alt="" class="rounded" style="height:36px;width:60px;object-fit:cover">@endif <div><span class="badge {{ $section->is_active ? 'bg-success' : 'bg-secondary' }} me-2">{{ $section->is_active ? 'Hiển thị' : 'Ẩn' }}</span><strong>{{ $section->title }}</strong><code class="ms-2">{{ $section->key ?: 'no-key' }}</code><div class="small text-muted mt-1">{{ $section->content ?: 'Chưa có mô tả.' }}</div></div></div><div><a class="btn btn-sm btn-soft-primary" href="{{ route('admin.homepage-sections.create', ['locale' => $locale, 'parent' => $section->id]) }}">Thêm section con</a><a class="btn btn-sm btn-soft-warning" href="{{ route('admin.homepage-sections.edit', $section) }}">Sửa</a><form class="d-inline" method="POST" action="{{ route('admin.homepage-sections.destroy', $section) }}">@csrf @method('DELETE')<button type="submit" class="btn btn-sm btn-soft-danger" onclick="return confirm('Xóa section này sẽ xóa section và section con tương ứng ở cả bốn ngôn ngữ. Bạn có chắc chắn?')">Xóa</button></form></div></div>
    @if($section->children->isNotEmpty())<div class="table-responsive"><table class="table table-sm align-middle mb-0"><tbody>@foreach($section->children as $child)<tr><td class="ps-4 text-muted"><i class="ri-corner-down-right-line"></i></td><td><strong>{{ $child->title }}</strong><code class="ms-2">{{ $child->key ?: 'no-key' }}</code></td><td>{{ $child->content ?: '—' }}</td><td><span class="badge {{ $child->is_active ? 'bg-success' : 'bg-secondary' }}">{{ $child->is_active ? 'Hiển thị' : 'Ẩn' }}</span></td><td class="text-end"><a class="btn btn-sm btn-soft-warning" href="{{ route('admin.homepage-sections.edit', $child) }}">Sửa</a><form class="d-inline" method="POST" action="{{ route('admin.homepage-sections.destroy', $child) }}">@csrf @method('DELETE')<button type="submit" class="btn btn-sm btn-soft-danger" onclick="return confirm('Xóa section con này ở cả bốn ngôn ngữ. Bạn có chắc chắn?')">Xóa</button></form></td></tr>@endforeach</tbody></table></div>@endif
</div>@empty<div class="text-center text-muted py-5">Chưa có section nào. Hãy thêm section chính đầu tiên.</div>@endforelse
</div></div>
@endsection
